linters-settings:
  gocritic:
    enabled-checks:
      - emptyStringTest
      - evalOrder
      - paramTypeCombine
      - preferStringWriter
      - sprintfQuotedString
      - stringConcatSimplify
      - yodaStyleExpr
  revive:
    rules:
      - name: line-length-limit
        arguments: [120]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - revive
      text: "line-length-limit:"

linters:
  enable:
    - thelper
    - gofumpt
    - gocritic
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - revive
